### ISSUE TITLE
Contacts page

### ISSUE THREAD

**Issue by deyan-a** [Teodor92/Project-Company-Life#11]
5. The user should see a Google maps with the location of the company. The address should be extracted as the value of the first contacts details entry that has the isPrimaryAddress flag set to true.

Q: In the case of no primary address being set, should we display the map at all and what should be the default display position?

**Comment by YanaSlavcheva** [comment]
Hello.
If there is no primary address set, just show the map and set the default display position to Sofia.

Cheers.
