### ISSUE TITLE
Job list admin panel

### ISSUE THREAD

**Issue by bpopnikolov** [Teodor92/Project-Company-Life#4]
Could you give more details about point 8 in the _List job applications administration_ user story? 

_"8. There must be an additional column for the email of the administrator that sent the application (not shown in the wireframe). When the administrator clicks the email, it opens a locally installed on the user machine mail client."_

More specifically what do you mean by **_"There must be an additional column for the email of the administrator that sent the application"_** ?

**Comment by Teodor92** [comment]
Hi @bpopnikolov 

This is a mistake, the following should say:

_"8. There must be an additional column for the email of the **USER** that sent the application (not shown in the wireframe)."_

Or in short, when a user applies for a job position, he/she must be registered. After the application is submitted we can display the email of the user that submitted it in the administration.

P.S. Updated the user story.
