### ISSUE TITLE
Duplicated description in stories

### ISSUE THREAD

**Issue by shdwskip** [Teodor92/Project-Company-Life#5]
In **List job ads administration** and **List links administration** both descriptions are: _This page allows administrators to view all the job ads in the application, add new ones and delete/edit existing ones._

Also, could you please provide more information about Links administration? We are not sure what are these links for?

Thank you!

**Comment by Teodor92** [comment]
Hi @shdwskip 

Fixed the incorrect wording: https://github.com/Teodor92/Project-Company-Life/commit/33ac5221d2a0261aaa23a30a431e089eb2d8e5fd

In short the the links are actually the buttons on the landing page. There are two types of links/buttons - action links/buttons that appear in the middle of the page and the social buttons/links that appear in the social buttons section of the page. The idea is that these buttons are going to be create dynamically from the administrator and rendered on the landing page using that data. 

For a more graphical representation, please refer to the [Landing page wireframe](https://github.com/Teodor92/Project-Company-Life/blob/master/specification/user-stories/landing-page.md).

Best,
Teodor
