### ISSUE TITLE
Job Applications Admin User Story

### ISSUE THREAD

**Issue by VladimirTumbev** [Teodor92/Project-Company-Life#8]
# What is the issue?

Hello Honeybee team,
In the user story 'job-applications-admin' it is stated that if an admin clicks on the Applications button in a job ad, they should be redirected to the specific job ads' applications, however in the 'List job ads administration' user story, there is no mentioning of an applications specific button for each job ad, only an Applications button in the navigation, which assumingly refers to all applications for all jobs.

Could you please provide clarification on which of the following scenarios should we focus on:

1) Each job ad in the 'List job ads administration' page should have an additional button called 'Applications', which takes the user to a page showing a list of all applications specific to this job ad
or,
2) Have an 'Applications' button in the navigation that lists all applications and keeping a reference (in a column for example) to the job they, the applications, refer to? 

Thank you in advance.

**Comment by YanaSlavcheva** [comment]
Hello, Vladimir.

In the user story [Job ad details](https://github.com/Teodor92/Project-Company-Life/blob/master/specification/user-stories/job-ad-details.md) we have:
`8. If the user is an administrator, he has an additional button Show all applications, that redirects him to the view job applications administration.`

Our suggestion is that you open the page with all applications for a specific job ads from this button.

Additionally (this is optional) for better usability you can add a column with a button `Applications` in the grid in [Job Ads](https://github.com/Teodor92/Project-Company-Life/blob/master/specification/user-stories/job-ads-admin.md) administration.

Does that answer Your question?

Best regards,
Yana
